
<img src="img/viu_logo.png" width="200">

## 01MIAR - Estructuras de datos, +Pandas

![logo](img/python_logo.png)

*Ivan Fuertes / Franklin Alvarez*

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'3.0.2'

# Operaciones en pandas

In [5]:
rand_matrix = np.random.randint(6,size=(4,6))
frame = pd.DataFrame(rand_matrix , columns=list('ABCDEF'))
display(frame)

   A  B  C  D  E  F
0  1  5  3  2  2  3
1  4  0  0  4  2  1
2  3  0  1  2  4  3
3  1  3  3  0  5  3

In [6]:
# Pandas utiliza numpy por debajo. Podemos acceder a un nparray equivalente a través de values
print(frame.values)
print(type(frame.values))

[[1 5 3 2 2 3]
 [4 0 0 4 2 1]
 [3 0 1 2 4 3]
 [1 3 3 0 5 3]]
<class 'numpy.ndarray'>

#### Búsqueda

In [ ]:
# El operador in busca en columnas (DataFrame como dic, busca en claves)
'E' in frame

In [ ]:
# Puedes buscar valores en el dataframe que pertenezcan a una lista con el método isin
lista = [2, 3, 4]
search_mask = frame.isin(lista)

display(search_mask) # --> mask de respuesta (valores que son 3 o 2)
display(frame[search_mask])

In [ ]:
# Contar el número de ocurrencias
# Por columnas
print(search_mask.sum())
print()

# Por filas
print(search_mask.sum(axis=1))
print()

# En total
# print("Se han encontrado {} ocurrencias".format(search_mask.sum().sum()))
print("Se han encontrado {} ocurrencias".format(search_mask.values.sum()))

#### Ordenación

In [ ]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
indx_col = list('ABCD')

shuffle(indices) # mezcla indices
shuffle(indx_col) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=indx_col, index=indices)
display(frame)

In [ ]:
# ordenar por índice
frame.sort_index(ascending=True, inplace=True)
display(frame)

In [ ]:
#ordenar por columna
frame.sort_index(axis=1, ascending=True, inplace=True)
display(frame)

In [ ]:
# ordenar filas por valor en columna
frame.sort_values(by='A', ascending=True, inplace=True)
display(frame)

In [ ]:
# ordenar columnas por valor en fila
frame.sort_values(by=1, axis=1, ascending=True, inplace=True)
display(frame)

In [ ]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C']:
    print(x)

#### Ranking
- Construir un ranking de valores

In [ ]:
display(frame)

In [ ]:
display(frame)
# display(frame.rank())
# display(frame.rank(axis=1))
display(frame.rank(method='average', axis=1))

# Operaciones

Operaciones matemáticas entre objetos

In [ ]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

In [ ]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

In [ ]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

In [ ]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

In [ ]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

Operadores aritméticos solo válidos en elementos aceptables

In [ ]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

Operaciones entre Series y DataFrames

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

In [ ]:
primera_fila = df.iloc[0, :]
primera_fila.name = "Primera fila"
print(primera_fila)
print()

# uso común, averiguar la diferencia entre una fila y el resto
# display(df - primera_fila)
display(df.sub(primera_fila, axis=1))

In [ ]:
# # Por columnas cómo se restaría
primera_columna = df['A']
primera_columna.name = "Primera columna"
print(primera_columna)
print()

display(df.sub(primera_columna, axis=0))

pandas se basa en NumPy, np operadores binarios y unarios son aceptables 

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Si queremos aplicar una función a cada columna (o fila) utilizamos `apply`

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

In [ ]:
def max_min(x):
    return x.max() - x.min()

serie = pd.Series()
serie.name = "Diferencia max min"
for col in frame:
    serie[col] = max_min(frame[col])
    
print(serie)
print()

serie2 = frame.apply(max_min) # diferencia por columna
serie2.name = "Diferencia max min usando apply"
print(serie2)

In [ ]:
# Las funciones lambda están pensadas para estos casos
serie3 = frame.apply(lambda x : x.max() - x.min()) # diferencia por columna
serie3.name = "Diferencia max min usando apply y función lambda"
print(serie3)

In [ ]:
# El método apply también puede aplicarse por filas definiendo el eje de iteración
serie4 = frame.apply(lambda x : x.max() - x.min(), axis=1)
serie4.name = "Diferencia max min usando apply, función lambda y por filas"
print(serie4)

# Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame

| Operación | Descripción |
|:----------|:------------|
| count | Número de valores no NaN |
| describe | Conjunto de estadísticas sumarias|
| min, max | Valores mínimo y máximo |
| argmin, argmax | Índices posicionales del valor mínimo y máximo |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo |
| sum | Suma de los elementos |
| mean | Media de los elementos |
| median | Mediana de los elementos |
| mad | Desviación absoluta media del valor medio |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos |
| cumsum | Suma acumulada de los elementos |
| diff | Diferencia aritmética de los elementos |

In [11]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30], 
               "puntos" : [98,12,68,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
print("Número de elementos no NaN:")
print(frame.count())    # datos generales de elementos
print()
print("Estadística de elementos numéricos:")
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    68.0      M
3  Carlos    30     NaN      M

Número de elementos no NaN:
nombre    4
edad      4
puntos    3
genero    4
dtype: int64

Estadística de elementos numéricos:

            edad     puntos
count   4.000000   3.000000
mean   27.250000  59.333333
std    10.996211  43.650124
min    11.000000  12.000000
25%    25.250000  40.000000
50%    32.000000  68.000000
75%    34.000000  83.000000
max    34.000000  98.000000

In [7]:
# Podemos acceder a estos valores
edad_media = frame.describe()['edad']['mean']
print(edad_media)

KeyError: 'edad'

In [8]:
# operadores básicos
print(frame.sum())
print()
print("Ignorando datos no numéricos")
print(frame.sum(numeric_only=True))

A     9
B     8
C     7
D     8
E    13
F    10
dtype: int64

Ignorando datos no numéricos
A     9
B     8
C     7
D     8
E    13
F    10
dtype: int64

In [ ]:
frame.mean(numeric_only=True)

In [ ]:
frame.cumsum()

In [ ]:
frame.count(axis=1)

In [ ]:
print(frame['edad'].std())

In [ ]:
frame['edad'].idxmax()

In [ ]:
frame['puntos'].idxmin()

In [ ]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())

mask = frame['puntos'] == frame['puntos'].max()
display(frame[mask])

idm = frame['puntos'].idxmax()
display(frame.loc[idm])

In [ ]:
frame["ranking"] = frame["puntos"].rank(method='max', ascending=False)  
display(frame)

## Agregaciones

Las agregaciones son operaciones que realizamos sobre *categorías*.

Ejemplo, la columna `genero` sólo puede tener un número finito de valores (masculino "M" o femenino "F"), por lo que podemos deducir que es una columna categórica.

In [ ]:
# El método groupby() se encarga de dividir los datos por categorías según la columna que se indique.
display(frame)
datos_por_genero = frame.groupby('genero')
print(datos_por_genero) # Es un elemento no realizado esperando por una función de agregación

In [1]:
# En este caso, la función de agregación es count(), que se aplicará a cada categoría
# count_por_genero = datos_por_genero.count()
# display(count_por_genero)

# Otras funciones de agregación
display(datos_por_genero.mean(numeric_only=True))
display(datos_por_genero.max())

NameError: name 'datos_por_genero' is not defined

In [ ]:
# podemos incluso obtener distintos estadísticos con el método aggregate
display(datos_por_genero[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

In [ ]:
# El método filter te permite hacer operaciones sobre los grupos y descartar aquellos que no cumplan una condición determinada
frame2 = datos_por_genero.filter(lambda x : x['edad'].mean() > 30)
display(frame2)

In [ ]:
# Sin utilizar lambda sería:
def media(x):
    display(x) # x será un dataframe
    return x["edad"].mean() > 30

frame3 = datos_por_genero.filter(media)
# display(frame3)

In [ ]:
# No hay categorías Nan, el groupby los descarta por defecto
df = frame.groupby('puntos').count()
display(df)

## Correlaciones

pandas incluye métodos para analizar correlaciones
- Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2) --> medida de correlación entre los datos de ambos objetos

### Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG
- Objetivo:
  - Determinar las correlación del milleage per gallons (mpg) de los coches respecto a otras especificaciones técnicas

In [4]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, sep='\\s+', header=None,
            names = ['mpg', 'cilindros', 'desplazamiento','potencia',
            'peso', 'aceleracion', 'año', 'origen', 'nombre'],
            na_values='?', engine='c')
print(mpg_data)

      mpg  cilindros  desplazamiento  potencia    peso  aceleracion  año  \
0    18.0          8           307.0     130.0  3504.0         12.0   70
1    15.0          8           350.0     165.0  3693.0         11.5   70
2    18.0          8           318.0     150.0  3436.0         11.0   70
3    16.0          8           304.0     150.0  3433.0         12.0   70
4    17.0          8           302.0     140.0  3449.0         10.5   70
..    ...        ...             ...       ...     ...          ...  ...
393  27.0          4           140.0      86.0  2790.0         15.6   82
394  44.0          4            97.0      52.0  2130.0         24.6   82
395  32.0          4           135.0      84.0  2295.0         11.6   82
396  28.0          4           120.0      79.0  2625.0         18.6   82
397  31.0          4           119.0      82.0  2720.0         19.4   82

     origen                     nombre
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
393       1            ford mustang gl
394       2                  vw pickup
395       1              dodge rampage
396       1                ford ranger
397       1                 chevy s-10

[398 rows x 9 columns]

In [ ]:
display(mpg_data.sample(5))
mpg_data.info()

In [ ]:
display(mpg_data.describe(include='all'))

### Correlaciones entre valores

In [ ]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

In [ ]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

### Correlaciones entre todos los valores

In [ ]:
mpg_data.corr(numeric_only=True)

In [ ]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

In [ ]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1, vmax=1)

In [ ]:
# correlación más negativa
corr_data.idxmin()

In [ ]:
# correlación más positiva
corr_data.idxmax()  #consigo misma....

In [ ]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
corr_data = corr_data.where(~np.eye(len(corr_data), dtype=bool))

# Ya no tenemos la diagonal igual a 1
display(corr_data)
corr_data.idxmax()

In [ ]:
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1, vmax=1)

In [12]:
mpg_corr = corr_data['mpg'].drop('mpg')
mpg_corr.name = "Correlaciones del mpg respecto a las otras característica"
print(mpg_corr)

NameError: name 'corr_data' is not defined

## Ejercicios

- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb
- Soluciones en: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles-with-solutions.ipynb